# coding: utf-8
import bioscrape, pickle
m = bioscrape.types.Model(filename = "/Users/sclamons/Dropbox/Murray_Lab/Modeling/plasmid_replication/models/simple_colE1_for_lineages.xml")
import numpy as np
ts = np.arange(0, 5, 0.01)
bioscrape.simulator.py_simulate_model(ts, Model = m, stochastic = True, return_dataframe = False)
postpickled_M = pickle.loads(pickle.dumps(m))
postpickled_M.check_species()
print(postpickled_M.check_species())
postpickled_M.get_params2index()
postpickled_M.get_species2index()
postpickled_M.get_species_list()
postpickled_M.get_species_array()
postpickled_M.get_param_list()
postpickled_M.get_params()
postpickled_M.get_species()
postpickled_M.get_number_of_params()
m = bioscrape.types.Model(filename = "/Users/sclamons/Dropbox/Murray_Lab/software/bioscrape/tests/temp/serializable_model.xml")
postpickled_m = pickle.loads(pickle.dumps(m))
postpickled_m.get_params2index()
postpickled_m.get_species2index()
postpickled_m.get_species_list()
postpickled_m.get_species_array()
postpickled_m.get_param_list()
postpickled_m.get_params()
postpickled_m.get_species()
postpickled_m.get_number_of_params()
postpickled_m.get_parameter_values()
postpickled_m.get_parameter_dictionary()
postpickled_m.get_species()
postpickled_m.get_species_dictionary()
postpickled_m.get_number_of_species()
postpickled_m.get_reactions()
p = postpickled_m.get_reactions()[0]
prop = p[0]