# Manually run this action
name: PyPI Release

on:
  workflow_dispatch:

jobs:
  pypi-publish:
    runs-on: ubuntu-latest
    environment: Release Deploy

    steps:
      - uses: actions/checkout@v4
      
      - name: Build inside manylinux_2_28 container
        run: |
          docker run --rm -v $(pwd):/io -w /io quay.io/pypa/manylinux_2_28_x86_64 /bin/bash -c "\
            /opt/python/cp312-cp312/bin/python -m pip install --upgrade pip build auditwheel && \
            /opt/python/cp312-cp312/bin/python -m pip install -r requirements.txt && \
            /opt/python/cp312-cp312/bin/python -m build --wheel --outdir /io/dist && \
            auditwheel repair /io/dist/*.whl --plat manylinux_2_28_x86_64 --wheel-dir /io/dist"
            rm -f /io/dist/*linux_x86_64.whl && \


      - name: List built wheels (debugging step)
        run: ls -lh dist/

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN}}
